# University of California, Berkeley
# Chem 274B: Software Engineering Fundamentals for
#            Molecular Sciences 
# December 2023
# 
# Creators: Qi Tifany Chu, Sean Bray and Elizabeth Gilson

# Directory Path: 274B_final_project/Lib 

# "clean" target to remove .a files in this directory. 


clean:
	rm *.a